feat(RadioGroup): now supports centered content OR left/top aligned content
GetTerminus/terminus-ui pull request #1612
Opened 2019-07-31 15:51 UTC by benjamincharity

ISSUES CLOSED: #1570

- Added flag to allow control over centered content
- Converted a couple extra tests to integration since I was in there
- Remove unneeded ternary for disabled class
- Added `as any` to tests as needed for TS

2019-08-01 12:57 UTC, shani-terminus requested changes

2019-08-01 12:57 UTC, shani-terminus commented on terminus-ui/radio-group/src/radio-group.component.md
> +By default the content is centered when in visual mode. Setting `centeredContent` to `false` will use standard top/left alignent.
misspelled alignMent

2019-08-01 14:43 UTC, atlwendy approved these changes

2019-08-05 15:35 UTC, shani-terminus approved these changes

2019-08-05 16:11 UTC, merged